/**
 * Work Graph Types - Domain model for executable engineering work items.
 *
 * The Work Graph represents the executable engineering state of the repository.
 * Unlike a task list, it models dependencies, parallelism, risk, knowledge generation.
 *
 * @module core/types/work-graph
 */

// ============================================================================
// Node Types
// ============================================================================

/**
 * Atomic engineering work categories.
 * Each node type represents one unit of engineering effort.
 */
export enum WorkNodeType {
  // Core engineering
  Research = "research",
  Prototype = "prototype",
  Implementation = "implementation",
  Testing = "testing",

  // Documentation
  Documentation = "documentation",
  ArchitectureDecision = "adr",

  // Analysis
  Benchmark = "benchmark",
  Review = "review",
  Profiling = "profiling",

  // Quality
  Refactoring = "refactoring",
  Validation = "validation",

  // Planning
  Planning = "planning",
  Design = "design",

  // Infrastructure
  Deployment = "deployment",
  Experiment = "experiment",

  // Reverse engineering
  ReverseEngineering = "reverse_engineering",

  // Knowledge production
  KnowledgeCapture = "knowledge_capture",
}

/**
 * Work node states following the full lifecycle.
 * Nodes never disappear - history matters.
 */
export enum WorkNodeState {
  Planned = "planned",
  Ready = "ready",
  Running = "running",
  Waiting = "waiting",
  Blocked = "blocked",
  Review = "review",
  Completed = "completed",
  Cancelled = "cancelled",
  Failed = "failed",
  Archived = "archived",
}

// ============================================================================
// Work Node
// ============================================================================

/**
 * A node in the Work Graph representing one atomic unit of engineering work.
 */
export interface WorkNode {
  /** Unique node identifier */
  id: string;

  /** Display title */
  title: string;

  /** Detailed description of the work */
  description: string;

  /** Category of engineering work */
  type: WorkNodeType;

  /** Priority level (1-10, 10 = highest) */
  priority: number;

  /** Current state in the lifecycle */
  state: WorkNodeState;

  /** Estimated cost budget (in normalized compute units) */
  estimatedCost: number;

  /** Estimated token budget */
  estimatedTokens: number;

  /** Estimated time budget in milliseconds */
  estimatedTimeMs: number;

  /** Required capabilities to execute this node */
  requiredCapabilities: string[];

  /** Node IDs that must complete before this node can start */
  dependencies: string[];

  /** Risk level (0-1, 1 = highest risk) */
  risk: number;

  /** Complexity score (1-100) */
  complexity: number;

  /** Confidence in estimates (0-1, 1 = most confident) */
  confidence: number;

  /** Expected deliverables */
  expectedDeliverables: string[];

  /** Acceptance criteria for completion */
  acceptanceCriteria: string[];

  /** Assigned worker ID (set during scheduling) */
  assignedWorkerId?: string;

  /** Assigned provider name (set during scheduling) */
  assignedProvider?: string;

  /** Execution history entries */
  executionHistory: NodeExecutionRecord[];

  /** Knowledge artifacts generated by completing this node */
  knowledgeGenerated: string[];

  /** Timestamps for state transitions */
  createdAt: string;
  updatedAt: string;
  startedAt?: string;
  completedAt?: string;

  /** Metadata for arbitrary extension */
  metadata: Record<string, unknown>;
}

/**
 * Records one execution attempt of a node.
 */
export interface NodeExecutionRecord {
  /** Attempt number (1-based) */
  attempt: number;

  workerId: string;
  providerName: string;
  startedAt: string;
  finishedAt: string;
  durationMs: number;
  tokensUsed?: number;
  costIncurred: number;
  success: boolean;
  errorMessage?: string;
}

// ============================================================================
// Work Graph
// ============================================================================

/**
 * The complete work graph - an executable representation of engineering.
 */
export interface WorkGraph {
  /** Unique graph identifier */
  id: string;

  /** Version number (incremented each planning cycle) */
  version: number;

  /** Human-readable name */
  name: string;

  /** Associated mission ID */
  missionId: string;

  /** All nodes in the graph */
  nodes: Map<string, WorkNode>;

  /** Adjacency list: nodeId -> set of dependent node IDs */
  dependents: Map<string, Set<string>>;

  /** Metadata for arbitrary extension */
  metadata: Record<string, unknown>;

  /** Lifecycle state of the entire graph */
  state: WorkGraphLifecycleState;

  createdAt: string;
  updatedAt: string;
}

/**
 * Top-level lifecycle state of a work graph.
 */
export enum WorkGraphLifecycleState {
  Creating = "creating",
  Active = "active",
  Paused = "paused",
  Complete = "complete",
  Abandoned = "abandoned",
}

// ============================================================================
// Node Queries & Filters
// ============================================================================

/**
 * Filters for querying work nodes.
 */
export interface WorkNodeFilter {
  types?: WorkNodeType[];
  states?: WorkNodeState[];
  priorityMin?: number;
  priorityMax?: number;
  capability?: string;
  hasDependencies?: boolean;
  isBlocked?: boolean;
  assignedToWorker?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Query results for work graph operations.
 */
export interface WorkGraphQueryResult {
  /** Matching nodes */
  nodes: WorkNode[];

  /** Total count (including non-matching) */
  totalCount: number;

  /** Offset used for pagination */
  offset: number;

  /** Limit used for pagination */
  limit: number;
}

// ============================================================================
// Graph Operations
// ============================================================================

/**
 * Result of adding a node to the graph.
 */
export interface NodeAddedResult {
  success: true;
  node: WorkNode;
  unblockedNodes: string[];
}

export interface NodeAddConflictError {
  success: false;
  error: "node_exists" | "invalid_dependency" | "circular_dependency";
  details: string;
}

export type AddNodeResult = NodeAddedResult | NodeAddConflictError;

/**
 * Result of removing a node from the graph.
 */
export interface NodeRemovedResult {
  success: true;
  nodeId: string;
  affectedNodes: string[];
}

// ============================================================================
// Priority Scoring
// ============================================================================

/**
 * Components used in priority scoring for work nodes.
 */
export interface PriorityScore {
  /** Base priority (1-10) */
  basePriority: number;

  /** Dependency boost (nodes with more dependents get boosted) */
  dependencyBoost: number;

  /** Blocking decay (waiting/blocked nodes get penalized) */
  blockingDecay: number;

  /** Recency bonus (newer ready nodes get slight bonus) */
  recencyBonus: number;

  /** Final composite score */
  totalScore: number;
}

/**
 * Configuration for the priority scoring algorithm.
 */
export interface PriorityScoringConfig {
  /** Weight for base priority (default: 1.0) */
  basePriorityWeight: number;

  /** Maximum dependency boost (default: 2.0) */
  maxDependencyBoost: number;

  /** Blocking penalty factor (default: 0.5) */
  blockingPenalty: number;

  /** Recency half-life in milliseconds (default: 1 hour) */
  recencyHalfLifeMs: number;
}

// ============================================================================
// Default scoring configuration
// ============================================================================

export const DEFAULT_SCORING_CONFIG: PriorityScoringConfig = {
  basePriorityWeight: 1.0,
  maxDependencyBoost: 2.0,
  blockingPenalty: 0.5,
  recencyHalfLifeMs: 3_600_000, // 1 hour
};

// ============================================================================
// Node ID Generation
// ============================================================================

/**
 * Format for generated node IDs.
 * Pattern: prefix-sequential-number
 */
export interface NodeIdConfig {
  /** Prefix (e.g., "research", "impl", "test") */
  prefix: string;
  /** Starting counter (default: 1) */
  startCounter?: number;
}

let nodeCounter = 0;

/**
 * Generates sequential node IDs.
 * Thread-safe within a single process context.
 */
export function generateNodeId(config?: Partial<NodeIdConfig>): string {
  const prefix = config?.prefix ?? "task";
  nodeCounter++;
  return `${prefix}-${nodeCounter}`;
}

// ============================================================================
// Factory Functions
// ============================================================================

/**
 * Creates a new WorkNode with default values.
 */
export function createWorkNode(
  title: string,
  description: string,
  type: WorkNodeType,
  options?: {
    id?: string;
    priority?: number;
    dependencies?: string[];
    requiredCapabilities?: string[];
    estimatedCost?: number;
    estimatedTokens?: number;
    estimatedTimeMs?: number;
    metadata?: Record<string, unknown>;
  }
): WorkNode {
  const {
    id: customId,
    priority = 5,
    dependencies = [],
    requiredCapabilities = [],
    estimatedCost = 100,
    estimatedTokens = 10_000,
    estimatedTimeMs = 3_600_000, // 1 hour
    metadata = {},
  } = options ?? {};

  const now = new Date().toISOString();

  return {
    id: customId ?? generateNodeId(),
    title,
    description,
    type,
    priority: Math.max(1, Math.min(10, priority)),
    state: WorkNodeState.Planned,
    estimatedCost,
    estimatedTokens,
    estimatedTimeMs,
    requiredCapabilities,
    dependencies,
    risk: 0.5,
    complexity: 50,
    confidence: 0.7,
    expectedDeliverables: [],
    acceptanceCriteria: [],
    executionHistory: [],
    knowledgeGenerated: [],
    createdAt: now,
    updatedAt: now,
    metadata,
  };
}

/**
 * Creates a new WorkGraph with default values.
 */
export function createWorkGraph(
  name: string,
  missionId: string
): WorkGraph {
  const now = new Date().toISOString();
  return {
    id: generateNodeId({ prefix: "wg" }),
    version: 1,
    name,
    missionId,
    nodes: new Map(),
    dependents: new Map(),
    metadata: {},
    state: WorkGraphLifecycleState.Creating,
    createdAt: now,
    updatedAt: now,
  };
}